<?php 



echo "---------------------------" . "<br>";
echo "User ID : " . $_GET['userid'] . " [This is user id from database / fb id] " . "<br>";
echo "---------------------------" . "<br>";
echo 'PaymentId : ' . $_GET['paymentId'] . "[Generated by PayPal - uniq value for each payment]". "<br>"; 
echo "---------------------------" . "<br>";
echo 'Token : ' . $_GET['token'] . "[Generated by PayPal  : Merchant Token]". "<br>";
echo "---------------------------" . "<br>";
echo 'PayerID : ' . $_GET['PayerID'] . "[PayerID from PayPal Database]". "<br>";
echo "---------------------------" . "<br>";
echo "---------------------------" . "<br>";
echo "---------------------------" . "<br>";
?>